### ISSUE TITLE
Where to license larger dataset? 

### ISSUE THREAD

**Issue by MAVProxyUser** [stephansturges/MAVERICC#1]
I'd like to process this image set with your model... please advise. 

DJI AWS flight log photo leak: Extended + sound & instructions to reproduce.
https://www.youtube.com/watch?v=CRbgBItfZpo

**Comment by stephansturges** [comment]
the model is free, you can follow the steps in the Readme to process your dataset.

**Comment by MAVProxyUser** [comment]
I'm not looking for the "free" model, rather the larger "dataset" you mention and its resulting files.  

"I'm not going to release the dataset for the time being

This public release comes with a full-sized Yolov7-e6e .pt model file"

I assumed my request was covered under: 
"I make money by charging for:

help with training additional detection classes,
retraining for your specific hardware,"

Are you not offering for pay consulting to do what I am asking? I need Pretrained data with more than just "airplane" as the main class detection.

**Comment by stephansturges** [comment]
I think you are misusing the term "dataset": I _do_ provide services as a freelancer to help people deploy my models or to train AI models for specific tasks, but I don't propose to sell the dataset used to train any of my public models that are here on Github. If you want to run a model trained on many classes on that dataset above I would suggest you start with https://github.com/stephansturges/WALDO
